# Generated by Django 4.2.7 on 2023-11-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_number', models.CharField(max_length=50, unique=True, verbose_name='Номер купона')),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('participants_surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('participants_middleName', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
