# Generated by Django 4.2.7 on 2023-11-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coupon_participant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
